dudykr/stc

README.md
The location from which the `check.sh` and `release-time.sh` scripts can be run wasn't quite right.
Just a small update to the README
=> fix a small typo in README.md

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/tests/pass/class/inheritance/methods-from-object-1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/fn/args/contextuallyTypedBindingInitializer-1.swc-stderr
Correctly type check expressions like:
```ts
let a: string = notDefined.toString();
```
```
error[TS2304]: NoSuchVar {
span: Span {
lo: BytePos(
18,
),
hi: BytePos(
28,
),
ctxt: #0,
},
name: notDefined#1,
}
--> a.ts:1:17
|
1 | let a: string = notDefined.toString();
```
This is one of the false positive I'm hitting to get `tests/conformance/controlFlowNullishCoalesce.ts` to work.
=> Validate object in `obj.toString()` case

crates/stc_ts_types/src/lib.rs
- Change `Type::new_union_without_dedup` to prevent creating an invalid type.
=> fix(ts/types): Fix `Type::new_union_without_dedup`

crates/stc_ts_file_analyzer/src/analyzer/expr/unary.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
let x: { a?: number | string, b: number | string } = { b: 1 };
delete x.a;
delete x.b;
```
```
error[TS2790]: DeleteOperandMustBeOptional {
span: Span {
lo: BytePos(
85,
),
hi: BytePos(
88,
),
ctxt: #0,
},
}
--> a.ts:4:8
|
4 | delete x.b;
|        ^^^
```
See https://github.com/microsoft/TypeScript/pull/37921
=> feat(ts/analyzer): delete operand must be optional

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/tests.rs, crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_file_analyzer/tests/pass/types/inference/genericContextualTypes1/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/inference/genericContextualTypes1/1.ts, crates/stc_ts_file_analyzer/tests/pass/types/inference/genericContextualTypes1/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/inference/genericContextualTypes1/2.ts, crates/stc_ts_file_analyzer/tests/pass/types/union/unionTypeReduction2/5.swc-stderr, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, cspell.json
This PR moves the reversing logic for the variance of function parameters from `assign_to_fn_like` to `assign_param`, to fix logic for validating parameter counts.
=> fix(ts/analyzer): Fix assignment of function paramters

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
class A {
a?: A;
#b?: A;
constructor() {
this?.#b;           // Error
this?.a.#b;         // Error
}
}
```
```
error[TS18030]: DebugContext(
context: tried to access property to validate an optional chaining expression
context: tried to access property of an object (this;, id_ctx = Var)
Prop=Private(PrivateName { span: Span { lo: BytePos(114), hi: BytePos(116), ctxt: #0 }, id: b#0 })
OptionalChainCannotContainPrivateIdentifier {
span: Span {
lo: BytePos(
114,
),
hi: BytePos(
116,
),
ctxt: #0,
},
},
)
--> ./a.ts:8:15
|
8 |         this?.#b;           // Error
|               ^^
error[TS18030]: DebugContext(
context: tried to access property of an object to calculate type of a member expression
context: tried to access property of an object (A;, id_ctx = Var)
Prop=Private(PrivateName …
```
=> feat(ts/analyzer): disallow private identifiers in optional chain

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, src/main.rs
```ts
function a(x: number, y: string, z: void): void {}
a(4, "hello"); // ok
a(4, "hello", void 0); // ok
a(4); // not ok
function b(x: number, y: string, z: void, what: number): void {}
b(4, "hello", void 0, 2); // ok
b(4, "hello"); // not ok
b(4, "hello", void 0); // not ok
b(4); // not ok
```
```
error[TS2554]: ExpectedNArgsButGotM {
span: Span {
lo: BytePos(
131,
),
hi: BytePos(
135,
),
ctxt: #0,
},
min: 2,
max: Some(
3,
),
}
--> ./a.ts:10:1
|
10 | a(4); // not ok
| ^^^^
error[TS2554]: ExpectedNArgsButGotM {
span: Span {
lo: BytePos(
248,
),
hi: BytePos(
261,
),
ctxt: #0,
},
min: 4,
max: Some(
4,
),
}
--> ./a.ts:17:1
|
17 | b(4, "hello"); // not ok
| ^^^^^^^^^^^^^
error[TS2554]: ExpectedNArgsButGotM {
span: Span {
lo: BytePos(
273,
),
hi: BytePos(
294,
),
ctxt: #0,
},
min: 4,
max: …
```
=> fix(ts/analyzer): Fix false positive arg count error with `void` types

Cargo.lock, crates/stc_ts_file_analyzer/Cargo.toml, crates/stc_ts_file_analyzer/src/env.rs
This is to make iteration faster.
---
On m1 Max Macbook pro 64GB, the total time for `check.sh` dropped to 1m 36s from 2m 56s.
=> perf(ts/env): Use msgpack for caching

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/forgottenNew.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/members/objectTypeWithConstructSignatureAppearsToBeFunctionType.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/specifyingTypes/typeLiterals/arrayTypeOfFunctionTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/specifyingTypes/typeLiterals/arrayTypeOfFunctionTypes2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
We should distinguish this at some time in the future, but for now, I think we should not bother matching them.
=> test(ts/checker): Normalize more error codes

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/enums.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/type_cast.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/tests/conformance/declarationEmit/typePredicates/declarationEmitThisPredicates02.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/declarationEmit/typePredicates/declarationEmitThisPredicatesWithPrivateName02.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/enums/enumConstantMemberWithString.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/enums/enumConstantMemberWithTemplateLiterals.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/arrayLiterals/arrayLiterals.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/thisType/typeRelationships.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/assignmentCompatibility/covariantCallbacks.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Fix bivariant assignment.
- Allow casting anything to `{}`.
- Reduce false-positives related to enum initializers.
- Remove wrong instantiation logic.
---
I don't want to wait for CI
=> fix(ts/analyzer): Reduce trivial false-positives

crates/stc_ts_dts/tests/fixture.rs, crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/members/typesWithSpecializedCallSignatures.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/tuple/indexerWithTuple.ts.stats.rust-debug
- Fix deduplicating logic while checking for unknown properties on the RHS.
- Change the error code of the negative tuple index
=> fix(ts/analyzer): Fix trivial false positives

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_type_checker/tests/conformance/generators/generatorAssignability.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/asyncGenerators/types.asyncGenerators.es2018.1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/asyncGenerators/types.asyncGenerators.es2018.2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Use async iterator for `yield` in async generators.
=> fix(ts/analyzer): Use async iterator for `yield` in async generators

crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/declarationsAndAssignments.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringVariableDeclaration2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/186.
=> fix(ts/analyzer): Use empty tuple type for rest pattern with tuple initializer

crates/stc_ts_file_analyzer/src/analyzer/assign/class.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/interface.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/expander.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/var_decl.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/narrowing.rs, crates/stc_ts_file_analyzer/tests/pass/types/union/assertions-1-2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/union/assertions-1-2.ts, crates/stc_ts_file_analyzer/tests/pass/types/union/unionTypeReduction2/6.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/union/unionTypeReduction2/6.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/callWithSpread4.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/internalModules/DeclarationMerging/TwoInternalModulesThatMergeEachWithExportedInterfacesOfTheSameName.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionAndUnionTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionTypeAssignment.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/recursiveIntersectionTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- `assign`: Use `TypeLitMetadata.specified`.
- `extends`: Use correct logic for unknown RHS.
=> fix(ts/analyzer): Fix assignment of intersection types

Cargo.lock, crates/stc_ts_type_checker/scripts/_/notify.sh, crates/stc_ts_type_checker/scripts/check.sh, crates/stc_ts_type_checker/scripts/test.sh
If required, a user can use `./scripts/base.sh` instead of `./scriptes/test.sh` or `./scripts/check.sh`
=> test(ts/analyzer): Disable logging for base tests

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/util.rs, crates/stc_ts_file_analyzer/tests/pass/types/mapped/mappedTypeWithAny/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/mapped/mappedTypeWithAny/1.ts, crates/stc_ts_file_analyzer/tests/pass/types/mapped/mappedTypes4/1.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowBindingElement.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionReductionStrict.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionWithUnionConstraint.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/isomorphicMappedTypeInference.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeErrors.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeWithAny.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypes5.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypesArraysTuples.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/recursiveMappedTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/primitives/string/assignFromStringInterface2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Support array types in `keyof`.
- Normalize while assigning.
- Normalize the operand of `in keyof T`.
- Resolve indexed access types in type arguments before expanding a reference.
- Fix stack overflow of `convert_type_to_type_lit`.
- `get_property_names_for_mapped_type`: Support `null` and `undefined`.
=> feat(ts/analyzer): Improve handling of mapped types

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/var_decl.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameStaticAccessorsAccess.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameStaticAccessorssDerivedClasses.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameStaticMethodAssignment.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisAmbientModules.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisBlockscopedProperties.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisTypeIndexAccess.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisUnknown.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisUnknownNoImplicitAny.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/arrowFunction/emitArrowFunctionThisCapturing.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/arrowFunction/emitArrowFunctionThisCapturingES6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functions/arrowFunctionContexts.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/thisKeyword/typeOfThisGeneral.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/functions/functionParameterObjectRestAndInitializers.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRest.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRestParameter.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRestParameterES5.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/specifyingTypes/typeQueries/typeofThis.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeAndMemberIdentity/objectTypesIdentityWithCallSignatures3.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Remove needless normalizations.
- Ignore `globalThis` in some code paths.
- `access_property`: Support `globalThis`.
=> fix(ts/analyzer): Fix bugs related to `globalThis`

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/ty/type_facts.rs, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowOptionalChain/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowOptionalChain/2.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/specifyingTypes/typeQueries/typeofThis.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- `access_property`: Handle `undefined`.
- Add `TypeFacts::NEUndefinedOrNull` for member accesses.
- Support `TypeFacts::NENull` and `TypeFacts::NEUndefined`.
=> feat(ts/analyzer): Improve handling of type facts

crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/statements/switchStatements/switchStatements.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
We evaluate case clauses twice, once as an expression and once as a binary expression with `===`. But it results in duplicate variables. This PR fixes it.
=> fix(ts/analyzer): Fix handling of switch cases

crates/stc_ts_file_analyzer/src/analyzer/assign/cast.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/type_cast.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/ty/type_facts.rs, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameAndObjectRestSpread.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/controlFlow/dependentDestructuredVariables.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/rest/genericRestParameters3.ts.stats.rust-debug
- Add `preserve_union` to `NormalizeTypeOpts`.
- Use `normalize` instead of `expand_top_ref` for various functions.
- `get_iterator`: Adjust options passed to `normalize`.
- `convert_type_keys`: Support more types.
=> refactor(ts/analyzer): Use `normalize` instead of recursion

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowInOperator.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Support non-literal expressions for the LHS of an `in` expression.
- `key_matches`: Handle more computed keys.
=> feat(ts/analyzer): Support more LHS for `in`

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/type_cast.rs, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypes3.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Use `castable` for candidate check.
=> fix(ts/analyzer): Use correct logic for type narrowing with a property

crates/stc_ts_file_analyzer/src/analyzer/expr/function.rs, crates/stc_ts_file_analyzer/src/analyzer/props.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/dependentDestructuredVariables.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/thisType/thisTypeInObjectLiterals2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Add `apply_fn_type_ann`.
- Exclude `null` and `undefined` while determining type of methods.
=> feat(ts/analyzer): Pass more type annotations for function-like nodes

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/tests/pass/es6/arrowFunction/emitArrowFunctionThisCapturingES6/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/es6/arrowFunction/emitArrowFunctionThisCapturingES6/1.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/es6/arrowFunction/emitArrowFunctionThisCapturing.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/arrowFunction/emitArrowFunctionThisCapturingES6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): should use NoSuchProperty for globalThis.name

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/update.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/loops.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameFieldUnaryMutation.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/Symbols/symbolType2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/binaryOperators/inOperator/inOperatorWithInvalidOperands.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/binaryOperators/inOperator/inOperatorWithValidOperands.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFromPropNameInUnionType.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/valuesAndReferences/assignmentToParenthesizedIdentifiers.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/statements/VariableStatements/everyTypeWithAnnotationAndInvalidInitializer.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/statements/for-inStatements/for-inStatements.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownType1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Don't report `WrongTypeForLhsOfNumericOperation` for `unknown`.
- Fix the element type of the for-in loop with a type literal in the RHS.
- Change error code for invalid RHS of `in` operator.
- Allow assignment of various types to the `object` type.
- Use the correct error code for `never` in the RHS of `in` operator.
- Allow assignment to modules.
- Fix validation of the argument of update operations.
=> fix(ts/analyzer): Fix false positives related to types in special positions

crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/tests/pass/vars/destructuring/declarationsAndAssignments/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/vars/destructuring/declarationsAndAssignments/1.ts, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/declarationsAndAssignments.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/186.
=> fix(ts/analyzer): FIx types of vars declared with rest patterns

crates/stc_ts_errors/src/context.rs
It now prints the filename, line, and column.
=> feat(ts/analyzer): Improve `ctx!` macro

crates/stc_ts_file_analyzer/src/analyzer/mod.rs
Until now, when we look at the log, we have identified the location of the ts file.
However, only the column start position for that location was received, and the end position could not be obtained.
So I modified that part.
```rs
fn line_col(&self, span: Span) -> String {
if span.is_dummy() {
return "".into();
}
let loc = self.cm.lookup_char_pos(span.lo);
let hic = self.cm.lookup_char_pos(span.hi);
format!("({}:{}-{:?})", loc.line, loc.col_display + 1, hic.col_display + 1)
}
```
None
=> Update(ts/analzer): line_col should display end_column

crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/tests/pass/fn/impl/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/fn/impl/1.ts, crates/stc_ts_type_checker/tests/conformance/functions/functionImplementationErrors.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/functions/functionImplementations.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/keyofInferenceLowerPriorityThanReturn.ts.stats.rust-debug
Fixes type inference in this case:
```js
function(): number {
throw undefined
}
```
Originally, `throw` statements do not contribute to return values, and hence fails type inference. Only top-level throws are considered for now.
None known yet
None
=> fix(ts/analyzer): Top-level throws return `never`

crates/stc_ts_file_analyzer/tests/pass/es6/module/conflictsWithClass/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/es6/module/conflictsWithClass/1.ts, crates/stc_ts_ordering/src/stmt.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/bestCommonType/heterogeneousArrayLiterals.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Fixes the following example:
```js
class Foo {}
var foo: Foo
module Foo {
var inside = foo // 'foo' is not visible
}
```
While generating the dependency graph, `module Foo` used to be declared both as a type and a variable. This causes the module to be evaluated before the var-declaration, therefore making `foo` invisible to the module. However, it is [not currently valid to refer to modules in type annotations](https://www.typescriptlang.org/play?#code/LYewJgrgNgpgBAMRCOBvAUHLcYA8AOIATgC5wkCe+8SIAyiUQJYB2A5nALxwDOjrbdAF90ANwCGROADNkALkTI4AemVwWIMhKhMwYyTL7N2C2gDpaDYx1VwmJHjgLEHcSTAA0cABYgA7jCiMERAA), so they shouldn't be declared as one.
None known yet
Partially addresses #361
=> fix(ts/analyzer): Fix module declaration evaluation order

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeRelationships.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypes6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
handle these cases.
```
function f1<T>(x: Required<T>, y: T) {
y = x
x = y // error because `Require` has -? modifiers
}
function f2<T>(x: Partial<T>, y: T) {
y = x; // error because `Partial` has +? or ? modifiers
x = y;
}
```
=> fix(ts/analyzer): allow assigning to a mapped type that takes itself as arg

crates/stc_ts_file_analyzer/src/analyzer/expr/unary.rs, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownType1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Errors when performing unary op on unknown type.
e..g.
```ts
var x: unknown;
+x;  // Error
-x;  // Error
```
None
None
=> fix(ts/analyzer): Add error when performing unary op on unknown type

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/enums.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/ty/mod.rs, crates/stc_ts_file_analyzer/tests/pass-only/assign/enum-declaration/1.ts, crates/stc_ts_file_analyzer/tests/pass-only/assign/enum-declaration/2.ts, crates/stc_ts_type_checker/tests/conformance/types/typeAliases/interfaceDoesNotDependOnBaseTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_types/src/lib.rs, cspell.json
- Improve assignment logic for keyword types.
- Use `string | EnumVariant` for `Type::Enum` while assigning. 
- Merge enum variants from `normalize`.
=> fix(ts/analyzer): Fix assignment of `Type::Enum`

crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_storage/src/lib.rs, src/main.rs
I'm not 100% sure this is right but...
When using stc within a project, take a file that re-exports a var from another file.
For example:
```ts
// index.ts
export { myVar } from './store'
```
Currently we add the re-export to the store using the 2nd module Id (`./store`) instead of the id from `./index`(`./store`) instead of the id from`./index`.
https://github.com/dudykr/stc/blob/main/crates/stc_ts_file_analyzer/src/analyzer/export.rs#L352-L367
This causes a panic [here](https://github.com/dudykr/stc/blob/main/crates/stc_ts_storage/src/lib.rs#L176-L190). Since the module id passed in (`ctxt`) is not equal to the current module id.
This PR changes this behaviour and instead uses the current module id. This follows what's happening …
=> Use the correct module ID when re-exporting vars/types

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/tests/pass/controlFlow/typeGuards/typeGuardIntersectionTypes/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/intersection/intersectionWithUnionConstraint/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/intersection/intersectionWithUnionConstraint/2.ts, crates/stc_ts_file_analyzer/tests/visualize/types/typeRelationShips/typeInference/lab/union-of-intersections-assignable.swc-stderr, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowBindingElement.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsdoc/typeParameterExtendsUnionConstraintDistributed.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/salsa/typeFromPropertyAssignment31.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionOfUnionNarrowing.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionWithUnionConstraint.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/unionTypeInference.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Improve normalization of intersections.
- Improve assignment to intersection types.
---
implement intersection(`&`)
but, The code related to type param is ambiguous.
[https://www.typescriptlang.org/play?jsx=0#code/GYVwdgxgLglg9mABMATAHgFCMQFUQUwA8p8wATAZ0QqgCcYwBzRAH0TBAFsAjfW1xODL5gDfGQA0WRAFUCxUpWp0GzNhwA2GgUJFjJGAHwAKQgC5ciAGSyAlIgDe0wgG5EAeneJjeGzNvSGvhQiAD6FjT0TDrkemDiAhw8fIgAvIiuHl40MLTRbLqi8WQYAL5AA](https://www.typescriptlang.org/play?jsx=0#code/GYVwdgxgLglg9mABMATAHgFCMQFUQUwA8p8wATAZ0QqgCcYwBzRAH0TBAFsAjfW1xODL5gDfGQA0WRAFUCxUpWp0GzNhwA2GgUJFjJGAHwAKQgC5ciAGSyAlIgDe0wgG5EAeneJjeGzNvSGvhQiAD6FjT0TDrkemDiAhw8fIgAvIiuHl40MLTRbLqi8WQYAL5AA)
=> feat(ts/analzer): Implement Intersection

.github/workflows/CI.yml, .gitignore, .vscode/launch.template.json, CONTRIBUTING.md, crates/stc_ts_file_analyzer/examples/file.rs
I'm not sure if this is the best approach, but I believe it could be beneficial for new contributors. 
This PR adds a vscode debugging configuration to make it easier to check and learn how to run the type checker while developing. 
Currently, we usually use `./scripts/test.sh` to check a single file, but it takes a lot of time due to regression checking and generates enormous logs. Additionally, it can be difficult to run the type checker with the debugger. 
=> feat: add vscode debugging config

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/functions/strictBindCallApply1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownControlFlow.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownType1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Fix some panic that occurs when accessing the index type with a TS keyword like `string`
- make unknown assignable to `null | undefied | {}`
I will fix the extra_errors that were introduced by fixing the panic in another PR.
=> fix(ts/analyzer): make unknown assignable to null | undefied | {}

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowIfStatement.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/never/neverTypeErrors1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownControlFlow.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Always reports error when assigning T to never
Current:
```ts
var t: never;
t = undefined // ok (with strict null checks disabled)
t = null; // ok (with strict null checks disabled)
```
With this PR:
```ts
var t: never;
t = undefined // error
t = null; // error
```
**Extra Error:**
As a result of this change, there is an extra change error within stc/crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowIfStatement.ts .
This is caused, because tsc does not currently correctly infer that the `else` branch is unreachable hence causing the type of data to be never.
As you can see, TS correctly infers `data` as never, hence never -> never assignment succeeds 
Given this, I believe that the extra error is acceptable
None
**Related issue (if …
=> fix(ts/analyzer): Report error when assigning null/undefined to never

crates/stc_ts_dts/benches/fixture.rs, crates/stc_ts_dts/tests/fixture.rs, crates/stc_ts_env/src/lib.rs, crates/stc_ts_env/src/marks.rs, crates/stc_ts_file_analyzer/examples/file.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/tests.rs, crates/stc_ts_file_analyzer/src/env.rs, crates/stc_ts_file_analyzer/src/tests.rs, crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_file_analyzer/tests/builtin.rs, crates/stc_ts_file_analyzer/tests/perf.rs, crates/stc_ts_file_analyzer_macros/src/lib.rs, crates/stc_ts_storage/src/lib.rs, crates/stc_ts_type_checker/src/lib.rs, crates/stc_ts_type_checker/tests/conformance/internalModules/importDeclarations/invalidImportAliasIdentifiers.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/dts.rs, crates/stc_ts_type_checker/tests/error.rs, crates/stc_ts_type_checker/tests/pass.rs, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_checker/tests/tsc.rs, crates/stc_ts_type_checker/tests/types.rs
This PR removes `swc_globals` from `Env`. `Env` now does not manage `Marks`, so the user is responsible for providing the correct `Marks`. i.e. Created from the current `swc_common::GLOBALS`.
This change is made because the previous design was too error-prone. I found lots of mistakes due to `Env` in tests and fixed all of them.
Additionally, this PR exposes the top-level context to the `Analyzer`. The analyzer requires top-level context because of JSX.
=> refactor(ts/env): Remove swc globals from `Env`

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringWithLiteralInitializers.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/conditional/conditionalTypes2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
type Hmm = { a: string } extends {} ? string : never;
```
next type should be string, but this is never at stc
=> feat(ts/analyzer): Assign empty typeLit

crates/stc_ts_file_analyzer/src/analyzer/enums.rs, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypes4.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Allow member expr as the init of const enums

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment8(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment8(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment8(target=es2021).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment8(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment8(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment8(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment8(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFormTypeOfEqualEqualHasNoEffect.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFormTypeOfNotEqualHasNoEffect.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFormTypeOfOther.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
from [this test case](https://github.com/dudykr/stc/blob/main/crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFormTypeOfOther.ts)
```
A type guard of the form typeof x === s, where s is a string literal with any value but 'string', 'number' or 'boolean',
- when true, removes the primitive types string, number, and boolean from the type of x, or
- when false, has no effect on the type of x.
A type guard of the form typeof x !== s, where s is a string literal,
- when true, narrows the type of x by typeof x === s when false, or
- when false, narrows the type of x by typeof x === s when true.
```
=> fix(ts/analyzer): improve type guard of the form `typeof x === s`

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/props.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/Symbols/ES5SymbolProperty1.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/Symbols/ES5SymbolProperty2.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/Symbols/ES5SymbolProperty3.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/Symbols/ES5SymbolProperty4.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/Symbols/ES5SymbolProperty7.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/Symbols/symbolProperty48.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/Symbols/symbolProperty49.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/Symbols/symbolProperty58.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
`TS2471` is not relevant anymore.
https://github.com/microsoft/TypeScript/blob/4ba756fdc847115bc1ff5032ed06e9bed60f16b2/src/compiler/diagnosticMessages.json
=> fix: Remove symbol form check

crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/type_cast.rs, crates/stc_ts_file_analyzer/tests/pass-only/narrow/templateLiteralTypes3/1.ts, crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/tpl-in-1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/tpl-typoeof-1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/object/key/10.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2.swc-stderr, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypes3.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_types/src/lib.rs
Previously we were evaluating type-less template literals as a string literal, but it's wrong.
=> fix: Fix evaluation of template literals

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameStaticAccessorsAccess.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```javascript
class A {
static #prop = 1
}
A.#prop; // Error```
=> fix: Fix static property access with a private key

crates/stc_ts_file_analyzer/src/analyzer/convert/interface.rs, crates/stc_ts_file_analyzer/src/analyzer/decl_merging.rs, crates/stc_ts_type_checker/tests/types_pkg.rs
I'm not sure if this is correct, but these operations can be done later, at the usage side.
=> perf: Disable some checks for `.d.ts` files

crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs
This is required for `@types/react`, and it's quite close.
=> fix: Fix condition for exporting within a `.d.ts` file

crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownControlFlow.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
A literal intersected with a non-empty type literal is `never`.
=> feat: Improve reduction of intersection types

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/function/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock11(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock11(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock11(target=esnext).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameFieldDestructuredBinding(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameFieldDestructuredBinding(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameFieldDestructuredBinding(target=esnext).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/propertyMemberDeclarations/memberFunctionDeclarations/staticFactory1.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Create instance from `StaticThis` not `This`.
Check whether `this` is static beforehand and not during member access.
```typescript
class Base {
static create() {
return new this(); // StaticThis not This
}
}
```
=> fix: Fix evaluation of `this` and `staticthis`

crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/type_facts.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowTypeofObject.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Interesect type facts from each branch.
- Use `.entry().or_default() |=` instead of `.insert()` for type facts.
=> feat: Intersect type facts from `cons` and `alt` of an if stmt

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/tests/pass-only/controlwFlow/controlFlowOptionalChain/1.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Exclude `unknown` from narrowing with a comparison.
=> feat: Don't narrow type on equality comparison with `unknown`

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowBindingElement.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2018/es2018IntlAPIs.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisAmbientModules.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisBlockscopedProperties.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisGlobalExportAsGlobal.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisReadonlyProperties.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisUnknown.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2019/globalThisUnknownNoImplicitAny.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2020/es2020IntlAPIs.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_checker/tests/tsc.ignored.txt
This PR removes `NoSuchVar` for `globalThis` and fixes the dummy span issue of member expressions.
=> feat: Handle `globalThis` partially

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringArrayBindingPatternAndAssignment2.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/rest/genericRestParameters3.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/tuple/arityAndOrderCompatibility01.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Iteration over an array should work regardless of the symbol builtin, so I implemented it manually.
=> feat: Handle `Symbol.iterator` of `Array`

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameDuplicateField.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesUnique-3.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Handles duplicate static and instance names.
```typescript
class A {
#b = 1
static #b = 1 //TS2804
}
```
=> fix(ts/analyzer): Handle TS2804

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/tests/pass/exprs/typeGuards/typeGuardsWithInstanceOfByConstructorSignature/14.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/typeGuards/typeGuardsWithInstanceOfByConstructorSignature/14.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/dependentDestructuredVariables.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardsWithInstanceOfByConstructorSignature.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
interface FConstructor {
new (): any;
}
interface F {
foo: string;
bar: number;
}
declare var F: FConstructor;
var obj11: F | string;
if (obj11 instanceof F) {
// can't type narrowing, construct signature returns any.
obj11; // F | string Because F constructor is any
obj11.foo; // Error NoSuchVar
}
```
But, increase extra_error in DestructureVariables
So we need to solve the #552 issue first.
=> feat(ts/analyzer): Update instance of constructur ret_ty is any

crates/stc_ts_type_ops/src/lib.rs, crates/stc_ts_type_ops/src/replace.rs
The type replacer implements caching logic and it's based on the generics so it can be used to optimize other type operations.
=> feat: Add `replace_type` to type operations

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/constraint_reducer.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_type_ops/src/generalization/metadata.rs, crates/stc_ts_type_ops/src/tuple_to_array/metadata.rs
Patched operations:
- `rename_inferred`
- `prevent_tuple_to_array`
- `prevent_generalize`
- `generic::SingleTypeParamReplacer`
- `expr::ConstraintReducer`
=> perf: Migrate simple operations to `replace_type`

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs
=> fix: Don't generalize from `access_property`

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_file_analyzer/tests/pass-only/types/literal/numericStringLiteralTypes/1.ts, crates/stc_ts_file_analyzer/tests/pass-only/types/tuple/variadicTuples1/1.ts, crates/stc_ts_file_analyzer/tests/pass-only/types/tuple/variadicTuples1/2.ts, crates/stc_ts_file_analyzer/tests/pass-only/types/tuple/variadicTuples1/3.ts, crates/stc_ts_type_checker/tests/conformance/types/tuple/variadicTuples1.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_types/src/lib.rs
- Infer a type parameter as a single-element tuple if the parameter is of a rest type.
- Use `access_property` for the assignment of tuples.
- Use `access_property` for the inference of tuples.
- Improve `access_property` for tuples.
=> feat: Handle assignment of a tuple to a tuple

Cargo.lock, crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_types/Cargo.toml, crates/stc_ts_types/src/id.rs, crates/stc_ts_types/src/name.rs
This PR reduces memory usage of `Name` and optimizes for cases where the `Name` consists of a single `Id`.
=> perf: Refactor `Name` to prefer short names

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
In the code below, `o` cannot be `null` in the `cons` of the if statement.
```ts
function f21(o: Thing | null) {
if (o?.baz instanceof Error) {
o.baz;
}
}
```
=> feat: Add type facts for LHS of `instanceof`

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/type_cast.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/expander.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/ty/mod.rs, crates/stc_ts_file_analyzer/src/util/mod.rs, crates/stc_ts_type_ops/src/generalization/metadata.rs, crates/stc_ts_type_ops/src/tuple_to_array/metadata.rs, crates/stc_ts_types/src/lib.rs, crates/stc_utils/src/ext.rs
rust-analyzer has a limit of the token count of an expanded item, and it results in no autocompletion if the function is large. To workaround it, this PR removes `tracing::instrument` in favor of `tracing::span!().entered()`.
=> refactor: Don't use `tracing::instrument` for large functions

crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_type_ops/src/expansion/mod.rs, crates/stc_ts_type_ops/src/tuple_normalization.rs, crates/stc_ts_type_ops/src/tuple_to_array/metadata.rs, crates/stc_ts_types/src/lib.rs, crates/stc_ts_types/src/metadata.rs
- Moved `prevent_tuple_to_array` to `TupleMetadata` from `CommonMetadata`.
- Moved `no_expand` to `RefMetadata` from `CommonMetadata`.
- Moved `ignore_no_expand` to `RefMetadata` from `CommonMetadata`.
=> refactor: Move type-specific metadata to own types

crates/stc_ts_file_analyzer/src/analyzer/expr/function.rs, crates/stc_ts_file_analyzer/tests/pass/controlFlow/dependentDestructuredVariables/5.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/dependentDestructuredVariables/5.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/dependentDestructuredVariables.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
The following forms have been processed.
```ts
//@strict: true
type ReducerArgs =
| ["add", { a: number; b: number }]
| ["concat", { firstArr: any[]; secondArr: any[] }];
const reducer: (...args: ReducerArgs) => void = (op, args) => {
switch (op) {
case "add":
console.log(args.a + args.b);
break;
case "concat":
console.log(args.firstArr.concat(args.secondArr));
break;
}
};
```
=> feat: Improve handling of deep type guards

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance/types/union/unionTypeCallSignatures.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/union/unionTypeConstructSignatures.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Check for empty arguments while determining overload.
- Change the error code for 
```ts
var unionOfDifferentReturnType1: { (a: number): number; (a: string): string; } | { (a: number): Date; (a: string): boolean; };
unionOfDifferentReturnType1(true); // error in type of parameter
unionOfDifferentReturnType1(); // error missing parameter
```
=> feat: Use correct error code for overload resolution failure

crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_file_analyzer/src/analyzer/hoisting/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/import.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs
This PR moves fields of the `Analyzer` into `AnalyzerData` and stores the `AnalyzerData` as boxed to reduce `memmove.`
=> perf: Reduce `memmove` of `Analyzer`

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringAssignabilityCheck.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Potentially solves #592 . As far as I can tell, tuple types should be widened on iife if there's no type_ann . I tried to understand if there are other cases where they should be certainly widened but I couldn't find anything conclusive. Not sure if the changes are good enough to be mergeable. First time Im trying to contribute so I hope I didnt do anything horribly wrong.
Edit: I'm not sure if it's problematic that this error does not come from `get_iterator_inner` like in `tsc` but I couldn't figure out a way to do it from there
https://github.com/dudykr/stc/issues/592
=> potential fix to #592

crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/indexSignatureTypeInference.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Allow infering types from string map interface arg to number map param https://github.com/dudykr/stc/issues/594
=> fix: Index signature type inference

.github/workflows/CI.yml, crates/stc_ts_file_analyzer/scripts/auto-unignore.sh, crates/stc_ts_file_analyzer/scripts/base.sh, crates/stc_ts_file_analyzer/scripts/fast.sh, crates/stc_ts_file_analyzer/scripts/instrument/base.sh, crates/stc_ts_type_checker/scripts/base.sh, crates/stc_ts_type_checker/scripts/check.sh, crates/stc_ts_type_checker/scripts/instrument/types-pkg.sh, crates/stc_ts_type_checker/scripts/test.sh
As I refactored recursion of call/new expressions, we can now reduce the stack size.
=> chore: Reduce stack size to 8MB from 16MB for debug builds

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/es6/modules/defaultExportsCannotMerge04.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Adds TS2652
I have to admit my approach is kind of naive and only fixes the `defaultExportsCannotMerge04` so it will need to be edited to satisfy other `defaultExportsCannotMerge...` cases (for example `export default class`)
I can work on the other ones too, but
1. I don't know how to enable them because running `./scripts/test.sh defaultExportsCannotMerge` runs only `defaultExportsCannotMerge04`
2. I want to get some feedback as this is my first contribution in Rust
Should we make this one pretty and merge or should we tackle all `defaultExportsCannotMerge...` in one PR?
Closes: #591
=> fix: Fix error code for mixed default exports

crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/es6/modules/multipleDefaultExports04.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
When function is export default, it seems that it should return TS2323 regardless of whether the function name is the same or different, so I fixed it.
fix #664
=> fix: fix ts2323

crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_checker/tests/tsc.ignored.txt, crates/stc_ts_type_checker/tests/tsc.rs, scripts/stats/split-tests.sh
This PR
- ignores a flaky test case.
- makes conformance test suite by replacing `includes()` with `ends_with()`.
- improves script for splitting tests.
=> test(conformance): Make conformance test faster

crates/stc_ts_file_analyzer/src/analyzer/assign/class.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_file_analyzer/tests/tsc/issues/0xxx/741/1.ts, crates/stc_ts_file_analyzer/tests/tsc/issues/0xxx/741/1.tsc-errors.json, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithObjectMembersAccessibility.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithObjectMembersAccessibility.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
This PR introduces `report_assign_failure_for_missing_properties` in `AssignOpts` which can be used to select between `TS2322` and `TS2471` for the caller side.
=> fix: Improve selection of `TS2322` vs `TS2741`

crates/stc_ts_type_checker/tests/tsc.rs
```
22 unmatched errors out of 61 errors. Got 25 extra errors.
Wanted: [TscError { file: Some("tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts"), line: 13, col: 1, code: 2454 }, TscError { file: Some("tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts"), line: 17, col: 1, code: 2454 }, TscError { file: Some("tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts"), line: 21, col: 1, code: 2454 }, TscError { file: Some("tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts"), line: 25, col: 1, code: 2454 }, TscError { file: Some("tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts"), line: 38, col: 5, code: 2722 }, TscError { file: Some("tests/cases/conformance/controlFlow/controlFlowOptionalChain.ts"), line: 42, …
```
=> test: Hide filename from comparison

crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/tests/pass/es6/destructuring/destructuringWithLiteralInitializers/3.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/es6/destructuring/destructuringWithLiteralInitializers/3.ts
In #792, there was no type inference for the case `function f11([x=0, y] = []) {}`, so I added it.
=> Following #792, I added type inference.

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFromPropNameInUnionType.error-diff.json, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFromPropNameInUnionType.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
If `i` were an index signature, false facts should not be created unlike a union type. This caused the checker to be unable to access the type of `i` in the else clause.
```
interface Indexed {
[s: string]: any;
}
function f(i: Indexed) {
if ("a" in i) {
return i.a;
} 
return "c" in i && i.c; // error: i is inferred as never
}
```
=> fix(ts/analyzer): improve type-guard of 'in' operator

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/tests/tsc/issues/0xxx/979/1.ts, crates/stc_ts_file_analyzer/tests/tsc/issues/0xxx/979/1.tsc-errors.json
- Closes https://github.com/dudykr/stc/issues/979.
=> fix: Don't remove type params from functions in args

crates/stc_ts_file_analyzer/src/env.rs, crates/stc_ts_file_analyzer/tests/builtin.rs
=> refactor: Move caching logic for builtin to `BuiltIn` from `Env`

crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_file_analyzer/tests/errors/conformance/expressions/arrayLiterals/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/primitives/invalidAssignmentsToVoid.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/primitives/invalidVoidAssignments.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/primitives/invalidVoidValues.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/primitives/void1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithCallSignatures5/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithCallSignatures5/2.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithCallSignatures5/3.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithCallSignatures5/4.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithCallSignatures6/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithCallSignatures6/2.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithConstructSignatures4/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithConstructSignatures4/2.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/typeRelationships/typeInference/genericCallWithGenericSignatureArguments/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/union/withIndexSignature/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/union/withIndexSignature/2.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/conformance/types/union/withIndexSignature/3.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/issues/0xxx/415/1.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/issues/0xxx/415/2.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/issues/0xxx/415/3.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/issues/0xxx/415/4.swc-stderr, crates/stc_ts_file_analyzer/tests/errors/issues/0xxx/754/1.swc-stderr
Note that, currently, the rendered errors contain ANSI code.
=> test: Render errors for `base/errors` tests

crates/stc_ts_file_analyzer/src/analyzer/types/keyof.rs
=> fix: Fix `keyof` of tuple types

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypesPatterns.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypesPatterns.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
declare function nullishes(x: `${null | undefined}`): void;
nullishes("false"); // error should be reported
```
Adds error to above code. But if `boolean` is included in the union, no error
```ts
declare function nullishes(x: `${null | undefined | boolean}`): void;
nullishes("false"); // no error
```
=> fix: "false" | "true" when bool tpl

crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs, crates/stc_ts_file_analyzer/tests/pass-only/assign/tpl/1.ts
The following all failed
```ts
function f1(a: `100`) {
let x: `${number}`;
x = `${a}`; // incorrect 2322
}
function f2(a: `true`) {
let x: `${boolean}`;
x = `${a}`; // incorrect 2322
}
function f3(a: `false`) {
let x: `${boolean}`;
x = `${a}`; // incorrect 2322
}
```
This happened because the case of a `tpl` having 0 types was not handled.
No test case covered this so I added new ones in `pass-only`
=> fix: consider tpl with no types as string

crates/stc_ts_file_analyzer/src/analyzer/tsc_helper.rs, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypesPatterns.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypesPatterns.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
A `bigint` type of a tpl accepted values like `100_000` or `10e3` but that should not happen as it should only accept numeric strings (without separators or scientific notation)
```ts
declare function bigints(x: `${bigint}`): void;
bigints("100_000"); // should 2345
```
=> fix: numeric strings to tpl bigint type

crates/stc_ts_ordering/src/calc.rs, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRest.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRest.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
fix the ordering of statements when variables are erroneously declared multiple times
```javascript
var a = {}
var { } = a;
let b = 'a';
var {  [b]: soSo,  ...a } = a; // this errorneous re-declaration of var `a` hoists the line above the declaration of `b`
``` 
=> fix stmt ordering

crates/stc_ts_type_checker/tests/conformance.pass.txt
=> fix: missing conformance.pass property

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveConstraintOfIndexAccessType.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveConstraintOfIndexAccessType.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
function l<T extends {}, P extends keyof T>(s: string, tp: T[P]): void {
tp = s;
}
```
=> feat: Support accessing nom primitive constraint of an empty object

crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs
```rs
if r.is_num() {
match src.parse() {
Ok(v) => {
return Type::Lit(LitType {
span,
lit: RTsLit::Number(RNumber { span, value: v, raw: None }),
metadata: Default::default(),
tracker: Default::default(),
})
}
Err(..) => {
return Type::Keyword(KeywordType {
span,
kind: TsKeywordTypeKind::TsNumberKeyword,
metadata: Default::default(),
tracker: Default::default(),
})
}
}
}
```
=> fix: Fix panic from `parse().unwrap()` at generic inference

crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/externalModules/moduleResolutionWithExtensions.error-diff.json, crates/stc_ts_type_checker/tests/conformance/externalModules/moduleResolutionWithExtensions.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/externalModules/relativePathMustResolve.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/externalModules/relativePathToDeclarationFile.error-diff.json, crates/stc_ts_type_checker/tests/conformance/externalModules/relativePathToDeclarationFile.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/moduleResolution/allowImportingTsExtensions.error-diff.json, crates/stc_ts_type_checker/tests/conformance/moduleResolution/allowImportingTsExtensions.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/nonjsExtensions/declarationFileForHtmlFileWithinDeclarationFile.error-diff.json, crates/stc_ts_type_checker/tests/conformance/nonjsExtensions/declarationFileForHtmlFileWithinDeclarationFile.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/nonjsExtensions/declarationFileForHtmlImport.error-diff.json, crates/stc_ts_type_checker/tests/conformance/nonjsExtensions/declarationFileForHtmlImport.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeLocalMissing.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeLocalMissing.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_checker/tests/tsc.rs
=> feat: Implement error emission about existing file

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/props.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/ty/type_facts.rs, crates/stc_ts_type_ops/src/union_normalization.rs, crates/stc_ts_types/src/lib.rs
change 
```rs
Type::new_union(
span,
vec![
*r_prop_ty.clone(),
Type::Keyword(KeywordType {
span,
kind: TsKeywordTypeKind::TsUndefinedKeyword,
metadata: Default::default(),
tracker: Default::default(),
}),
],
)
```
to 
```rs
&Type::new_union(
span,
vec![*r_prop_ty.clone(), Type::undefined(span, Default::default())],
),
```
At first, we only worked with null and undefined
=> refactor: Use `Type::xx` as constructor for readability

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameAndPropertySignature.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
decrease panic
```ts
type A = {
#foo: string;
#bar(): string;
}
interface B {
#foo: string;
#bar(): string;
}
declare const x: {
#foo: number;
bar: {
#baz: string;
#taz(): string;
}
#baz(): string;
};
declare const y: [{ qux: { #quux: 3 } }];
```
=> feat: resolve privateNameAndPropertySignature.ts

crates/stc_ts_file_analyzer/src/analyzer/convert/interface.rs, crates/stc_ts_file_analyzer/tests/tsc/types/interface/interfaceDeclaration/1.ts, crates/stc_ts_file_analyzer/tests/tsc/types/interface/interfaceDeclaration/1.tsc-errors.json, crates/stc_ts_type_checker/tests/conformance/interfaces/interfaceDeclarations/interfaceExtendsObjectIntersectionErrors.error-diff.json, crates/stc_ts_type_checker/tests/conformance/interfaces/interfaceDeclarations/interfaceExtendsObjectIntersectionErrors.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
interface I31<T> extends T { x: string }
```
I have a concern.
The following functions cause duplicate error handling due to duplicate function calls.
```rs
#[validator]
impl Analyzer<'_, '_> {
fn validate(&mut self, d: &RTsInterfaceDecl) -> VResult<Type> {
let ty = self.with_child(ScopeKind::Flow, Default::default(), |child: &mut Analyzer| -> VResult<_> {
match &*d.id.sym {
"any" | "void" | "never" | "unknown" | "string" | "number" | "bigint" | "boolean" | "null" | "undefined" | "symbol" => {
child.storage.report(ErrorKind::InvalidInterfaceName { span: d.id.span }.into());
}
_ => {}
}
let mut ty = Interface {
span: d.span,
name: d.id.clone().into(),
type_params: try_opt!(d.type_params.validate_with(&mut *child).map(|v| v.map(Box::new))),
extends: …
```
=> feat: Remove extra error at `interfaceExtendsObjectIntersectionErrors`
