.cargo/config.toml, .gitignore, CONTRIBUTING.md, Cargo.lock, crates/rnode/Cargo.toml, crates/rnode/src/lib.rs, crates/rnode_macros/src/lib.rs, crates/stc_ts_ast_rnode/Cargo.toml, crates/stc_ts_builtin_macro/src/lib.rs, crates/stc_ts_builtin_types/Cargo.toml, crates/stc_ts_builtin_types/src/lib.rs, crates/stc_ts_env/Cargo.toml, crates/stc_ts_env/src/lib.rs, crates/stc_ts_file_analyzer/Cargo.toml, crates/stc_ts_file_analyzer/src/env.rs, crates/stc_ts_type_checker/scripts/release-time.sh, crates/stc_ts_type_checker/tests/tsc.timings.rust-debug, crates/stc_ts_types/Cargo.toml, crates/stc_ts_types/src/id.rs, crates/stc_ts_types/src/intrinsic.rs, crates/stc_ts_types/src/lib.rs, crates/stc_ts_types/src/metadata.rs, crates/stc_ts_types/src/module_id.rs, crates/stc_ts_types/src/type_id/symbol.rs, crates/stc_visit/src/lib.rs, cspell.json
=> perf(ts/env): Cache builtin types to speed up iteration

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/loops.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_type_checker/tests/conformance/types/asyncGenerators/types.asyncGenerators.es2018.1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/asyncGenerators/types.asyncGenerators.es2018.2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Use async iterator for async generators

crates/stc_ts_file_analyzer/src/analyzer/assign/builtin.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/tests/pass/types/mapped/nonPrimitiveAndTypeVariables/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/mapped/nonPrimitiveAndTypeVariables/1.ts, crates/stc_ts_generics/src/expander.rs, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeErrors.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveAndTypeVariables.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Previously we didn't visit some type nodes while expanding generics.
=> fix(ts/generics): Fix expansion of fully specified mapped types

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/tests/pass/nonPrimitive/nonPrimitiveNarrow/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/nonPrimitive/nonPrimitiveNarrow/1.ts, crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveNarrow.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): type narrowing should handle object => class

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/tests/pass/types/literal/numericStringLiteralTypes.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/literal/numericStringLiteralTypes.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/literal/numericStringLiteralTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
This issue handles #205 by implementing assign from Array to single-element Tuple of rest.
Fixes #205
=> Fixes #205

.github/FUNDING.yml, CONTRIBUTING.md, cspell.json
I mentored someone a lot, and I finally know what I should document
=> doc: Document debugging tips

crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/spread/objectSpreadSetonlyAccessor.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/spread/objectSpreadStrictNull.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat(ts/analyzer): Deduplicate RHS on type literal assignments

crates/stc_ts_module_loader/src/lib.rs, crates/stc_ts_type_checker/src/lib.rs, src/main.rs
- Closes https://github.com/dudykr/stc/issues/206.
=> fix(ts/modules): Fix stack overflow

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameAccessorssDerivedClasses.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/binaryOperators/comparisonOperator/comparisonOperatorWithIdenticalPrimitiveType.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/comparable/equalityStrictNulls.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> Change Error code for undefined in relative comparison - fixes #220

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/es6/spread/iteratorSpreadInCall4.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/callOverload.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/callWithSpread3.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/callWithSpread5.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analtyzer): Change error code invalid spread arguments

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_type_checker/.gitignore, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFromPropNameInUnionType.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Fix validation of RHS of an `in` operation

crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_types/src/lib.rs
=> feat(ts/analyzer): Improve handling of `unknown` in union/intersection

crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/assignmentCompatibility/assignmentCompatWithObjectMembersStringNumericNames.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_checker/tests/tsc.rs, crates/stc_ts_types/src/lib.rs
=> feat(ts/types): Improve `TypeEq` of `Key`

crates/stc_ts_base_type_ops/src/fix.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/expander.rs, crates/stc_ts_generics/src/expander.rs, crates/stc_ts_types/src/lib.rs
=> perf(ts/analyzer): Make `fix()` shallow

crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/tests/pass/types/tpl/stringMappingOverPatternLiterals/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/tpl/stringMappingOverPatternLiterals/1.ts, crates/stc_ts_generics/src/expander.rs, crates/stc_ts_type_checker/tests/conformance/classes/propertyMemberDeclarations/accessorsOverrideProperty8.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/literal/stringMappingOverPatternLiterals.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
This is a groundwork for https://github.com/dudykr/stc/issues/210
cc @ever0de
=> fix(ts/analyzer): Expand generics in `intrinsic` types

crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/tests/pass/types/inference/generatedContextualTypings/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/inference/generatedContextualTypings/4.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/exprs/call/overloadResolution/1.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/exprs/call/overloadResolution/2.swc-stderr, crates/stc_ts_type_checker/tests/conformance/es6/templates/taggedTemplateStringsWithOverloadResolution3.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es6/templates/taggedTemplateStringsWithOverloadResolution3_ES6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/overloadResolution.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/witness/witness.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Widen the return type of functions

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/tests/pass/exprs/object/this/thisTypeInObjectLiterals2/1.swc-stderr, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/thisType/looseThisTypeInFunctions.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/thisType/thisTypeErrors2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/thisType/thisTypeInObjectLiterals2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/thisType/thisTypeInTaggedTemplateCall.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat(ts/analyzer): Apply type facts to `this`

Cargo.lock, crates/stc_ts_lang_server/Cargo.toml, crates/stc_ts_lang_server/examples/lsp.rs, crates/stc_ts_lang_server/src/lib.rs, crates/stc_ts_lang_server/tests/lsp.rs, crates/stc_ts_testing/Cargo.toml, crates/stc_ts_testing/src/lsp.rs
I added test action for hover to verify
=> test(ts/lsp): Configure test system

crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2.swc-stderr, crates/stc_ts_type_checker/tests/conformance/types/literal/stringMappingOverPatternLiterals.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Remove the wrong code.
- Add a fast path for an assignment of a template literal to another.
=> feat(ts/analyzer): Improve handling of template literals

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/interface.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionThisTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Remove a wrong check for wrong interface implementation.
=> fix(ts/analyzer): Remove a wrong check for interface heritage

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/stringLiteral/stringLiteralTypesWithTemplateStrings02.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/334.
=> feat(ts/analyzer): Inline string literals in template literals

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRestNegative.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRestPropertyMustBeLast.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/342.
=> fix(ts/analyzer): Abort on non-last rest patterns

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/tests/pass/exprs/typeGuards/typeGuardOfFormIsType/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/typeGuards/typeGuardOfFormIsType/1.ts, crates/stc_ts_file_analyzer/tests/pass/exprs/typeGuards/typeGuardOfFormIsType/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/typeGuards/typeGuardOfFormIsType/2.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/expressions/typeGuards/typeGuardOfFormIsType.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Use the child type while narrowing.
=> feat(ts/analyzer): Improve type narrowing with type predicates

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/classes/constructorDeclarations/classConstructorAccessibility3.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
It's fine to assign to a variable initialized with a class.
=> fix(ts/analyzer): Reduce wrong checks

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/util.rs, crates/stc_ts_file_analyzer/tests/pass/classes/staticIndexSignature/staticIndexSignature1/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/classes/staticIndexSignature/staticIndexSignature1/1.ts, crates/stc_ts_type_checker/scripts/check.sh, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/staticIndexSignature/staticIndexSignature1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/staticIndexSignature/staticIndexSignature2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/staticIndexSignature/staticIndexSignature6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
It's indeed a lot of fun writing stc. :)
Fix #351
=> fix(ts/analyzer): handle static index signatures of a class

crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/tests/pass/async/es6/asyncMethodWithSuper_es6/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/async/es6/asyncMethodWithSuper_es6/1.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/async/es6/asyncMethodWithSuper_es6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): should return correct type of setter in super

crates/stc_ts_file_analyzer/src/analyzer/stmt/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/visit_mut.rs, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownType1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Don't store conditional facts for an expression statement

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/es6/spread/iteratorSpreadInArray6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/callWithSpread4.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/overloadResolution.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/overloadResolutionConstructors.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/parser/ecmascript5/parser15.4.4.14-9-2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/genericCallToOverloadedMethodWithOverloadedArguments.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Improve resolution of overloads

.github/FUNDING.yml, crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/tests/pass/exprs/object/objectLiteralNormalization/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/object/objectLiteralNormalization/1.ts, crates/stc_ts_type_checker/tests/conformance/expressions/objectLiterals/objectLiteralNormalization.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/dts.rs, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_ops/src/lib.rs, crates/stc_ts_type_ops/src/union_normalization.rs
`objectLiteralNormalization.ts` says `Normalization applies to nested properties`
=> feat(ts/analyzer): Normalize nested properties of a union

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/ty/type_facts.rs, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/2.ts, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/3.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/3.ts, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/4.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowTypeofObject/4.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowTypeofObject.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
`null` and `undefined` are special.
=> feat(ts/analyzer): Improve type narrowing with `==`

crates/stc_ts_base_type_ops/src/fix.rs, crates/stc_ts_errors/src/debug/mod.rs, crates/stc_ts_file_analyzer/scripts/instrument.sh, crates/stc_ts_file_analyzer/scripts/instrument/base.sh, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_type_checker/tests/tsc.rs
=> perf(ts/analyzer): Improve performance of debug build

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypes6.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/errors): Fix the error code for readonly properties

crates/stc_ts_errors/src/lib.rs
```
error[E0432]: unresolved import `crate::context::with_ctx`
--> crates/stc_ts_errors/src/lib.rs:28:5
|
28 | use crate::context::with_ctx;
|     ^^^^^^^^^^^^^^^^^^^^^^^^ no `with_ctx` in `context`
warning: unused import: `std::cell::RefCell`
--> crates/stc_ts_errors/src/context.rs:1:5
|
1 | use std::cell::RefCell;
|     ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `rnode::RNode`
--> crates/stc_ts_errors/src/debug/debugger.rs:3:5
|
3 | use rnode::RNode;
|     ^^^^^^^^^^^^
warning: unused import: `stc_ts_ast_rnode::RTsType`
--> crates/stc_ts_errors/src/debug/debugger.rs:4:5
|
4 | use stc_ts_ast_rnode::RTsType;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^
warning: unused imports: `Emitter`, `Node`, `text_writer::JsWriter`
--> …
```
=> Fix release builds

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/pat.rs, crates/stc_ts_type_checker/tests/conformance/types/rest/restTuplesFromContextualTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/tuple/variadicTuples1.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/172.
---
Sorry, @camc314
I forgot that #172 is assigned to you
=> feat(ts/analyzer): Fix handling of rest patterns

crates/stc_ts_errors/src/debug/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/scripts/check.sh, crates/stc_ts_type_checker/scripts/test.sh
I think this is important for productivity.
=> chore: Change logging level to show `unimplemented` messages

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringControlFlow.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/181.
=> feat(ts/analyzer): Improve assignment of a tuple to a tuple

crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/externalModules/exportNonLocalDeclarations.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): fix error code for exports with primitive names

crates/stc_ts_file_analyzer/src/analyzer/convert/interface.rs, crates/stc_ts_type_checker/tests/conformance/interfaces/interfaceDeclarations/interfaceWithMultipleBaseTypes.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Add match arm to prevent `extra_error`.
=> fix(ts/analyzer): prevent extra error from being reported in report_error_for_conflicting_parents

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance/expressions/functionCalls/overloadResolutionClassConstructors.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- added TS2334
- Implemented a check on the constraints in a class with generic types to ensure that the class only accepts valid input.
=> fix(ts/analyzer): add the check of the type args to satisfy constraints

crates/stc_ts_file_analyzer/src/env.rs
When eunning test or using stc, it will panic if the .stc builtin libs store fails to decode or fails to read.
This PR makes it much more defensive, logging the error instead of panicking if reading the store fails and continuing to reload the store with new data.
None
None
=> fix(ts/analyzer): Be defensive when loading builtin types

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/unionTypeInference.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/452.
=> fix(ts/analyzer): Fix assignment of intersection types

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/util.rs, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/1.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/1.ts, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/2.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/2.ts, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/3.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/3.ts, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/4.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/4.ts, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/5.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/types/literal/templateLiteralTypes2/5.ts, crates/stc_ts_generics/src/expander.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypes2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/literal/templateLiteralTypesPatterns.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeConstraints2.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_ops/src/generalization/metadata.rs, crates/stc_ts_type_ops/src/generalization/mod.rs, crates/stc_utils/src/stack.rs
- Closes https://github.com/dudykr/stc/issues/213.
=> feat(ts/analyzer): Implement type inference of template literals

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/tpl.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_types/src/convert.rs, crates/stc_ts_types/src/lib.rs
- Closes https://github.com/dudykr/stc/issues/458.
=> refactor(ts/types): Use `Atom` for `quasi` of `TplType`

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowIfStatement.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
resolve never assign never
add next code
```rs
if to.is_kwd(TsKeywordTypeKind::TsNeverKeyword) {
if let Type::Param(TypeParam { constraint: Some(ty), .. }) = rhs {
if ty.is_never() {
return Ok(());
}
}
fail!()
}
```
and 
replace next code
```rs
if u32::from(is_str) + u32::from(is_num) + u32::from(is_bool) >= 2 {
return Ok(());
}
```
to 
```rs
if u32::from(is_str) + u32::from(is_num) + u32::from(is_bool) >= 2 {
fail!()
}
```
=> feat(ts/analyzer): resolve constrolFlowIfStatement.ts

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownControlFlow.ts.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat(ts/analyzer): about never assign to never

crates/stc_ts_file_analyzer/src/analyzer/expr/jsx.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/src/validator.rs, crates/stc_ts_storage/src/lib.rs, crates/stc_ts_type_checker/tests/conformance/jsx/checkJsxIntersectionElementPropsType.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/jsxReactTestSuite.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxDynamicTagName1.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxDynamicTagName2.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxDynamicTagName3.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxDynamicTagName4.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxDynamicTagName6.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxElementResolution.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxIntrinsicAttributeErrors.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxLibraryManagedAttributes.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxTypeErrors.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/contextualTypes/jsxAttributes/contextuallyTypedStringLiteralsInJsxAttributes01.tsx.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, cspell.json
=> feat(ts/analyzer): Implement basic support for JSX

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock4(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlockUseBeforeDef1(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/thisAndSuperInStaticMembers1(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/thisAndSuperInStaticMembers1(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/thisAndSuperInStaticMembers2(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/thisAndSuperInStaticMembers2(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/thisAndSuperInStaticMembers3.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/thisAndSuperInStaticMembers4.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers2.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers3(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers3(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers3(target=es5).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers4(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers4(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers4(target=es5).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers5(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers5(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers5(target=es5).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers7(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers7(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers7(target=es5).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers8(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers8(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/instanceAndStaticMembers/typeOfThisInStaticMembers8(target=es5).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameStaticFieldCallExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): Allow using `this` in static property initilizers

crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/tests/pass/es2021/logicalAssignment/logicalAssignment7/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/es2021/logicalAssignment/logicalAssignment7/1.ts, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2021).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment6(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment6(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment6(target=es2021).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment6(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment7(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment7(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment7(target=es2021).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment7(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment4(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment4(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment4(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment6(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment6(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment6(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment7(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment7(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/esnext/logicalAssignment/logicalAssignment7(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Use correct type for `??=` and `||=`

crates/stc_ts_file_analyzer/src/analyzer/import.rs
just added annotation to avoid unsed clippy error in some cases while developing
=> chore: avoid unused clippy error

crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowBinaryOrExpression/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowBinaryOrExpression/1.ts, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowBinaryOrExpression/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowBinaryOrExpression/2.ts, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowBinaryOrExpression/3.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowBinaryOrExpression/3.ts
=> test(ts/base): Make base test faster

.vscode/settings.json, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/accessibility/protectedInstanceMemberAccessibility.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameAccessorsAccess.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameMethodAccess.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameNestedClassAccessorsShadowing.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameNestedClassFieldShadowing.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameNestedClassMethodShadowing.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesInGenericClasses.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesInNestedClasses-1.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesUnique-3.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/mixinAccessModifiers.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/expressions/thisKeyword/typeOfThisGeneral.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeAmbient.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/486.
=> fix: Fix stack overflow caused by nested usage of a class

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/expressions/valuesAndReferences/assignments.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Fix wrong error message about module(2631, 2708)
=> Fix(ts/analyzer): TS2708 should only occur on empty modules.

crates/stc_ts_file_analyzer/src/analyzer/expr/misc.rs
=> fix: Fix evaluation of instantiation expressions

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/thisType/thisTypeInFunctions.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Remove two panics in analyzer and add some more panic context (snippet & file).
=> Remove 2 panics

crates/stc_ts_env/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/jsx.rs, crates/stc_ts_file_analyzer/tests/base.rs, crates/stc_ts_type_checker/tests/conformance/jsx/jsxReactTestSuite.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxNoJsx.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxTypeErrors.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_type_checker/tests/tsc.rs, cspell.json
JSX is required to validate `@types/react`.
=> fix: Respect `jsx` option

crates/stc_ts_ordering/src/lib.rs, crates/stc_ts_ordering/src/stmt.rs, crates/stc_ts_ordering/src/types.rs
This is required for `@types/react`.
=> fix: Evaluate `declare global` first

crates/stc_ts_file_analyzer/src/analyzer/generic/expander.rs, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameMethodAsync.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowGenericTypes.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/generators/generatorReturnContextualType.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/asyncGenerators/types.asyncGenerators.es2018.1.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeRelationships.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix(ts/analyzer): resolve some panic

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_module_loader/src/lib.rs, crates/stc_ts_type_checker/scripts/instrument/types-pkg.sh, crates/stc_ts_type_checker/src/lib.rs, crates/stc_ts_type_checker/tests/types_pkg.rs, crates/stc_ts_types/src/lib.rs
This PR removes needless panic contexts.
=> perf: Make debug build faster

crates/stc_ts_file_analyzer/src/ty/type_facts.rs, crates/stc_ts_file_analyzer/tests/pass-only/types/unknown/unknownControlFlow/1.ts, crates/stc_ts_type_checker/tests/conformance/types/unknown/unknownControlFlow.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Inject `& ({} | null)` if `typeof` equals `object` 

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/jsx.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/tests/visualize/exprs/object/spread/1.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/exprs/object/spread/3.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/exprs/object/spread/4.swc-stderr, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameAndObjectRestSpread.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/literal/literalTypeWidening.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/spread/objectSpread.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/spread/spreadObjectOrFalsy.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/spread/spreadTypeVariable.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_types/src/name.rs
=> feat: Improve handling of object spreads

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/tests/pass-only/controlwFlow/controlFlowOptionalChain/2.ts, crates/stc_ts_file_analyzer/tests/pass-only/controlwFlow/controlFlowOptionalChain/3.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Use a separate list for exclusion while narrowing with equals

crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/tests/pass-only/conformance/types/spread/objectSpread/1.ts, crates/stc_ts_file_analyzer/tests/pass-only/conformance/types/spread/objectSpread/2.ts, crates/stc_ts_file_analyzer/tests/pass-only/conformance/types/spread/objectSpread/3.ts, crates/stc_ts_file_analyzer/tests/pass-only/conformance/types/spread/objectSpread/4.ts, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/types/spread/objectSpread.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Support appending type elements to an intersection

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/keyof.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_generics/src/expander.rs, crates/stc_ts_types/src/lib.rs
Panic is relatively rare at now, so this PR removes panic contexts to speed up debug build.
=> perf: Remove needless panic contexts

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/tests/pass-only/conformance/es6/destructuring/declarationsAndAssignments/1.ts, crates/stc_ts_file_analyzer/tests/pass-only/conformance/es6/destructuring/declarationsAndAssignments/2.ts, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/declarationsAndAssignments.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/specifyingTypes/typeQueries/typeofThis.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Interpret an array literal as a tuple in arguments

crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2020).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=es2021).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4(target=esnext).stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: keep actual_ty in logical assignment

crates/stc_ts_builtin_types/lib/es2022.d.ts, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/tests/builtin.rs
#530 
- Closes https://github.com/dudykr/stc/issues/530.
=> chore: enable es2022intl

crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/env.rs, crates/stc_ts_type_checker/tests/conformance/types/contextualTypes/methodDeclarations/contextuallyTypedClassExpressionMethodDeclaration01.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Closes https://github.com/dudykr/stc/issues/302.
=> feat: Pass type annotation to class members

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance/types/typeParameters/typeParameterLists/propertyAccessOnTypeParameterWithConstraints4.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeParameters/typeParameterLists/propertyAccessOnTypeParameterWithConstraints5.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Change error code for no property in a type paramter

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/rest/objectRest.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_types/src/lib.rs
=> feat: Support indexing string with a number-like string

crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/this.rs, crates/stc_ts_type_checker/tests/conformance/functions/parameterInitializersForwardReferencing1.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/functions/parameterInitializersForwardReferencing1_es6.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Fix evaluation of constructor parameters

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameAccessorsCallExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameFieldCallExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameMethodCallExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNameStaticAccessorsCallExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Support calling functions with `new`

crates/stc_ts_file_analyzer/src/analyzer/expr/function.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/tests/pass/controlFlow/dependentDestructuredVariables/4.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/dependentDestructuredVariables/4.ts, crates/stc_ts_type_checker/tests/conformance/controlFlow/dependentDestructuredVariables.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
```ts
//@strict: true
type Func = <T extends ["a", number] | ["b", string]>(...args: T) => void;
const f60: Func = (kind, payload) => {
if (kind === "a") {
payload.toFixed(); // error
}
if (kind === "b") {
payload.toUpperCase(); // error
}
};
```
=> feat: deep typeguard about destructor

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowOptionalChain.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
This PR adds an identical logic for `!==`.
=> feat: Improve type facts for `typeof`

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_type_checker/tests/conformance/expressions/valuesAndReferences/assignmentToParenthesizedIdentifiers.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Use correct error code for assignments to non-variable

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/interface.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/decl_merging.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/function/return_type.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/import.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/pat.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/type_param.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/ambient_decl.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/var_decl.rs, crates/stc_ts_file_analyzer/src/analyzer/types/keyof.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/ty/type_facts.rs, crates/stc_ts_type_checker/tests/types_pkg.rs
=> refactor: Introduce `Analyzer.config`

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_type_checker/tests/conformance/controlFlow/dependentDestructuredVariables.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
I resolve desctructure assigned about Interface Union
=> feat: Improve handling of deep type guards

crates/stc_ts_type_checker/src/loader/analyzer.rs, crates/stc_ts_type_checker/src/loader/mod.rs, crates/stc_ts_type_checker/tests/types_pkg.rs
=> feat(ts/loader): Treat `reference`s in a typing package as a cycle

crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_type_checker/tests/conformance/classes/propertyMemberDeclarations/strictPropertyInitialization.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Allow more types for a computed key

1.ts, crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_type_checker/tests/conformance/ambient/ambientExternalModuleInsideNonAmbient.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/ambient/ambientExternalModuleInsideNonAmbientExternalModule.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: TS2668 error for ambient module

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs
Now it also shows the normalized form.
=> refactor: Improve context of assignment

crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs, crates/stc_ts_file_analyzer/tests/pass-only/assign/mapped/recursive/1.ts, crates/stc_ts_type_checker/tests/conformance/types/mapped/isomorphicMappedTypeInference.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeErrors.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeRelationships.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeWithAny.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypes5.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypes6.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypesArraysTuples.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
This PR improves the expansion of mapped types and also improves the assignment logic related to mapped types.
=> fix: Fix expansion of mapped types

crates/stc_ts_file_analyzer/src/analyzer/assign/builtin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/await_expr.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/return_type.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/asyncGenerators/types.asyncGenerators.es2018.2.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/specifyingTypes/typeQueries/circularTypeofWithVarOrFunc.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
- Instantiate types while validating return types.
- Improve `get_awaited_type`.
- Optimize assignment of `Promise`.
=> feat: Instantiate return type while validating

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/expander.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/conditional/conditionalTypes2.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Fix normalization of an indexed access type with type parameter key

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/loops.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/es6/Symbols/symbolType13.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/statements/for-inStatements/for-inStatementsInvalid.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/never/neverTypeErrors1.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/never/neverTypeErrors2.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
fix next
```ts
declare function f4(): never;
for (const n in f4()) {}
```
But, I increase 1 error
I don't understand this error
follow the next code
```ts
for (var x in 42 ? d[x] : c[x]) { }
```
It's not written in error.json.
There should be an error. I think.
=> Fix: right hand side of statement must be any

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock9(target=es2015).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock9(target=es2022).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock9(target=es5).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/classes/classStaticBlock/classStaticBlock9(target=esnext).stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/witness/witness.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Fix the error code for a usage of property before init

crates/stc_ts_type_checker/benches/dts_libs.rs, crates/stc_ts_type_checker/scripts/release-time.sh, crates/stc_ts_type_checker/src/loader/mod.rs, crates/stc_ts_type_checker/tests/tsc.rs, crates/stc_ts_type_checker/tests/types_pkg.rs, src/main.rs
This. is a groundwork for multi-file tests.
=> feat: Make module loader accept file loader

crates/stc_ts_testing/src/conformance.rs, crates/stc_ts_type_checker/Cargo.toml, crates/stc_ts_type_checker/scripts/check.sh, crates/stc_ts_type_checker/scripts/test.sh, crates/stc_ts_type_checker/src/loader/mod.rs, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
`v0.1.0` will not support checking javascript files.
=> test: Disable javascript tests

crates/stc_ts_errors/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_type_checker/tests/conformance.pass.txt, crates/stc_ts_type_checker/tests/conformance/dynamicImport/importCallExpressionDeclarationEmit1.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/dynamicImport/importCallExpressionDeclarationEmit3.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/dynamicImport/importCallExpressionInUMD5.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/dynamicImport/importCallExpressionReturnPromiseOfAny.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/dynamicImport/importCallExpressionShouldNotGetParen.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Validate the first argument of dynamic imports

crates/stc_ts_type_checker/scripts/errors/stats.py
Usage: `./scripts/errors/stats.py`.
```
Extra: {
"TS2339": 260,
"TS2304": 180,
"TS2322": 134,
"TS2307": 121,
"TS0": 83,
"TS2345": 64,
"TS2503": 24,
"TS2532": 21,
"TS2741": 12,
"TS2528": 11,
"TS2349": 10,
"TS7027": 10,
"TS2461": 9,
"TS2300": 6,
"TS2531": 6,
"TS2350": 5,
"TS2663": 4,
"TS2769": 4,
"TS2323": 4,
"TS2367": 3,
"TS2403": 3,
"TS2372": 2,
"TS2365": 2,
"TS2555": 2,
"TS2699": 2,
"TS2610": 2,
"TS18013": 2,
"TS2451": 2,
"TS2490": 2,
"TS2701": 2,
"TS2320": 2,
"TS7022": 1,
"TS7053": 1,
"TS2660": 1,
"TS2420": 1,
"TS2309": 1,
"TS2407": 1,
"TS17009": 1,
"TS2525": 1,
"TS2554": 1,
"TS2430": 1
}
Required: {
"TS2322": 341,
"TS2430": 127,
"TS2411": 121,
"TS2345": 117,
"TS2339": 116,
"TS2367": 100,
"TS2818": 92,
"TS2403": 81,
"TS2300": 80,
"TS2365": 80,
"TS2532": 52,
"TS2373": …
```
=> chore: Add a script to print stats per error code

Cargo.lock, crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_type_checker/Cargo.toml, crates/stc_ts_type_checker/tests/conformance/externalModules/exportAssignmentMergedInterface.error-diff.json, crates/stc_ts_type_checker/tests/conformance/externalModules/exportAssignmentMergedInterface.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeAmbient.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeAmbient.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeAmbientMissing.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/import/importTypeAmbientMissing.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
Fixes https://github.com/dudykr/stc/issues/717
=> fix: Allow using types for export assignments

Cargo.lock, crates/stc_ts_file_analyzer/tests/builtin.rs
I want to check the performance difference caused by https://github.com/servo/string-cache/pull/268.
=> chore(deps): Update `string-cache`

crates/stc_ts_file_analyzer/src/analyzer/assign/function.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_types/src/lib.rs
This PR adds assertions for cheap clones to more places and fixes panics related to them.
=> perf: Reduce needless clones

crates/stc_ts_file_analyzer/src/analyzer/generic/expander.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs
I extracted this from https://github.com/dudykr/stc/pull/751 because I think it will be a long-term PR.
=> feat: Add `preserve_keyof` to `NormalizeTypeOpts`

Cargo.lock, crates/stc_arc_cow/Cargo.toml, crates/stc_arc_cow/src/freeze.rs, crates/stc_arc_cow/src/lib.rs, crates/stc_ts_file_analyzer/src/analyzer/assign/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/enums.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/keyof.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/util.rs, crates/stc_ts_type_checker/tests/conformance/externalModules/amdImportNotAsPrimaryExpression.error-diff.json, crates/stc_ts_type_checker/tests/conformance/externalModules/amdImportNotAsPrimaryExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/externalModules/commonJSImportNotAsPrimaryExpression.error-diff.json, crates/stc_ts_type_checker/tests/conformance/externalModules/commonJSImportNotAsPrimaryExpression.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug, crates/stc_ts_types/src/convert.rs, crates/stc_ts_types/src/is.rs, crates/stc_ts_types/src/lib.rs
This PR also refactors code using `find_type` with `enum_name` to use `def` directly.
=> perf: Use `ArcCow` for `Enum`

crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_file_analyzer/src/analyzer/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs, crates/stc_ts_storage/src/lib.rs
=> refactor: Rename methods of `Storage`

crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/tests/pass/es6/destructuring/destructuringWithLiteralInitializers/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/es6/destructuring/destructuringWithLiteralInitializers/2.ts, crates/stc_ts_file_analyzer/tests/pass/exprs/call/destructuringParameterDeclaration1ES5/4.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/fn/args/default/destructuringParameterDeclaration1ES5iterable-4.swc-stderr, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringWithLiteralInitializers2.error-diff.json, crates/stc_ts_type_checker/tests/conformance/es6/destructuring/destructuringWithLiteralInitializers2.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
fix #720 
Fixed issue #720 by changing the `add_vars` function.
#720
=> fix: fix #720 Change type inference for function parameters

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/optional_chaining.rs, crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowOptionalChain/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/controlFlow/controlFlowOptionalChain/2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/es6/destructuring/destructuringWithLiteralInitializers/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-3-1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-3.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-4.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-5.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-6.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/exprs/optionalChaining/access-7.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/fn/args/default/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/generic/call-chain-1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/generic/call-chain-2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/guards/controlFlowOptionalChain/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/mapped/4-2.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/mapped/5.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/objectTypeLiteral/methodSignatures/overload/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/predicate/controlFlowOptionalChain/1.swc-stderr, crates/stc_ts_file_analyzer/tests/pass/types/predicate/controlFlowOptionalChain/2.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/controlFlow/controlFlowOptionalChain/1.swc-stderr, crates/stc_ts_file_analyzer/tests/visualize/fn/args/default/1.swc-stderr, crates/stc_ts_types/src/lib.rs
=> refactor: Introduce `Type::union_with_undefined`

crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_file_analyzer/src/analyzer/convert/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/loops.rs, crates/stc_ts_types/src/lib.rs
=> feat: Use `key_matches` while matching keys

crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/unary.rs, crates/stc_ts_type_checker/tests/conformance/jsx/checkJsxChildrenProperty3.error-diff.json, crates/stc_ts_type_checker/tests/conformance/jsx/checkJsxChildrenProperty3.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/checkJsxChildrenProperty4.error-diff.json, crates/stc_ts_type_checker/tests/conformance/jsx/checkJsxChildrenProperty4.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/jsx/tsxCorrectlyParseLessThanComparison1.error-diff.json, crates/stc_ts_type_checker/tests/conformance/jsx/tsxCorrectlyParseLessThanComparison1.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Expand type arguments passed to member expressions

crates/stc_ts_file_analyzer/src/analyzer/assign/type_el.rs, crates/stc_ts_type_checker/tests/conformance/types/keyof/keyofAndIndexedAccess.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/keyof/keyofAndIndexedAccess.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeConstraints2.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeConstraints2.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> fix: Assign the object of indexed access type to type elements

crates/stc_ts_file_analyzer/src/analyzer/export.rs, crates/stc_ts_ordering/src/stmt.rs, crates/stc_ts_type_checker/tests/conformance/es6/modules/exportBinding.error-diff.json, crates/stc_ts_type_checker/tests/conformance/es6/modules/exportBinding.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Handle evaluation dependency of named exports

crates/stc_ts_file_analyzer/src/analyzer/class/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/await_expr.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/jsx.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/expr/object.rs, crates/stc_ts_file_analyzer/src/analyzer/props.rs, crates/stc_ts_file_analyzer/src/analyzer/stmt/var_decl.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs
=> perf: Reduce deep clone

clippy.toml, crates/stc_ts_file_analyzer/src/analyzer/expr/array.rs, crates/stc_ts_file_analyzer/src/analyzer/generalize.rs, crates/stc_ts_type_checker/tests/conformance/generators/generatorExplicitReturnType.error-diff.json, crates/stc_ts_type_checker/tests/conformance/generators/generatorExplicitReturnType.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Use correct logic for getting the element type from an iterator

crates/stc_ts_file_analyzer/src/analyzer/generic/inference.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_type_checker/tests/conformance/types/conditional/conditionalTypes2.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/conditional/conditionalTypes2.stats.rust-debug, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/genericCallWithOverloadedFunctionTypedArguments2.error-diff.json, crates/stc_ts_type_checker/tests/conformance/types/typeRelationships/typeInference/genericCallWithOverloadedFunctionTypedArguments2.stats.rust-debug, crates/stc_ts_type_checker/tests/tsc-stats.rust-debug
=> feat: Implement more type inference

Cargo.toml, crates/stc_ts_errors/src/lib.rs, scripts/try.sh, src/main.rs
I found several issues while trying stc on material-ui
=> fix: Fix usage of `swc_common::GLOBALS`

crates/stc_ts_file_analyzer/src/analyzer/expr/call_new.rs, crates/stc_ts_file_analyzer/src/analyzer/generic/mod.rs, crates/stc_ts_file_analyzer/src/analyzer/types/mapped.rs
=> refactor: Cleanup

crates/stc_ts_file_analyzer/tests/base.rs
Added because it's hard to find without `actual error`
=> test: Update `conformance` test error message format

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
remove unused code and duplicate code at analyzer/expr/bin.rs - validate_bin_expr
=> refactor: Reduce unused code

crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
remove duplicate code
We were generating the same type every quarter
=> refactor: Remove duplicate code
